project:
  type: website

website:
  title: "NeuroPsyTools"
  image: img/homepage_2024-09-13.png
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This is a highly *developmental* version. Return back for further updates."
    type: primary
    position: below-navbar
  description: "A place for neuropsychology nerds to assemble."
  google-analytics:
    tracking-id: "G-3TJ48XKDR9"
    anonymize-ip: true
    storage: none
  reader-mode: true
  favicon: img/favicon-color.ico
  twitter-card: 
    image: img/homepage_2024-09-13.png
    card-style: summary_large_image
    creator: "@chrisgaskell92"
  site-url: https://neuropsytools.com
  search: 
    location: navbar
    type: overlay
  navbar:
    background: secondary
    foreground: primary
    search: true
    back-to-top-navigation: tr
    logo: img/favicon-grey.ico
    left:
      - href: index.qmd
        text: Home
      - href: pages/apps.qmd
        text: Apps
      - href: pages/resources.qmd
        text: Resources
      #- href: pages/blog.qmd
      #  text: Blog
      #- href: pages/author.qmd
      #  text: Author
  page-footer: 
    left: "Copyright 2024, NeuroTools"
    right:
      - icon: github
        href: https://github.com/chris-gaskell/neuro-tools
      - icon: twitter
        href: https://twitter.com/chrisgaskell92
    center:
      - href: pages/author.qmd
        text: Maintainer
    border: true
    background: secondary
    foreground: primary


# theming options: https://quarto.org/docs/output-formats/html-themes.html#dark-mode
format:
  html:
    theme:
      light: cerulean
      dark: darkly
    #css: styles.css
    toc: true
    toc-depth: 2
    fontsize: 1.1em
    linestretch: 1.7
    #include-after-body: ../footer.html

editor: visual

