project:
  type: website

# options here: https://quarto.org/docs/reference/projects/websites.html
website:
  title: "NeuroPsyTools"
  image: front-image.png
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Warning** - This is a highly *developmental* version of NeuroPsyTools. Return back for further updates."
    type: secondary
    position: below-navbar
  description: "A place for neuropsychology nerds to assemble."
  google-analytics: "UA-9692446052"
  reader-mode: true
  favicon: img/favicon-color.ico
  twitter-card:
    image: https://neuropsytools.com
    card-style: summary
    creator: "@chrisgaskell92"
  site-url: https://neuropsytools.com
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    foreground: secondary
    search: true
    #back-to-top-navigation: tr
    logo: img/favicon-grey.ico
    left:
      - href: index.qmd
        text: Home
      - href: pages/apps.qmd
        text: Apps
      - href: pages/resources.qmd
        text: Resources
      # - href: pages/reactable.qmd
      #   text: Reactable
  page-footer:
    left: "Copyright 2024, NeuroTools"
    right:
      - icon: github
        href: https://github.com/chris-gaskell/neuro-tools
      - icon: twitter
        href: https://twitter.com/chrisgaskell92
    center:
      - href: pages/author.qmd
        text: Maintainer
    border: true
    background: primary
    foreground: secondary


# theming options: https://quarto.org/docs/output-formats/html-themes.html#dark-mode
format:
  html:
    theme:
      light: [cerulean, styles/styles.scss]
      dark: darkly
    toc: true
    toc-depth: 2
    fontsize: 1.1em
    linestretch: 1.7

editor: visual
