project:
  type: website

website:
  title: "NeuroTools"
  #   cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
  # google-analytics:
  #   tracking-id: "G-XXXXXXX"
  #   anonymize-ip: true
  reader-mode: true
  favicon: files/favicon.ico
  twitter-card: true
  #image: favicon.png
  #card-style
  #creator
  #site
  #site-url: https://example.com
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    search: true
    back-to-top-navigation: true
    page-footer: 
      border: false
      background: false
      left: "Copyright 2024, NeuroTools" 
      # right: 
      #   - icon: github
      #     href: https://github.com/
      #   - icon: twitter 
      #     href: https://twitter.com/ 
    #logo: img/favicon-brain_2.png
    #logo-alt: 
    #logo-href: 
    # navbar:
    #   tools:
    #     - icon: twitter
    #       href: https://twitter.com
    #     - icon: github
    #       menu:
    #         - text: Source Code
    #           url:  https://code.com
    #         - text: Report a Bug
    #           url:  https://bugs.com
    left:
      - href: pages/landing.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: pages/apps.qmd
        text: Apps
      # - href: pages/blog.qmd
      #   text: Blog        
      - href: pages/blog.qmd
        text: Blog
    # right:
    #   - href: extra.qmd
    #     text: Extras
  # body-header: | 
  #   This page brought to you by <https://example.com>
  # margin-header: |
  #   more ![Logo image](/img/logo.png)

# theming options: https://quarto.org/docs/output-formats/html-themes.html#dark-mode
format:
  html:
    theme:
      light: [cerulean, styles.scss]
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    fontsize: 1.1em
    linestretch: 1.7

editor: visual

