---
title: "Resources"
---

# General

# Blogs

+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
| Tool / Application                                             | Description                                                                                                                     | Contributor                        |
+================================================================+=================================================================================================================================+====================================+
| [Easy Report](https://npscoresheet-b0f9fbefac84.herokuapp.com) | **Easy Report** transforms reporting into a seamless, efficient process, allowing you to focus on delivering valuable insights. | [Alexandra Davis](#alexneuropsych) |
+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
|                                                                |                                                                                                                                 |                                    |
+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
|                                                                |                                                                                                                                 |                                    |
+----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+------------------------------------+

: Tools and Applications for Clinical Neuropsychology.

# Books

# Community

# Inclusivity

# Innovation

+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Article / Resources                                                                                           | Description                                                              | Contributor/s                                                                                                                                                        |
+===============================================================================================================+==========================================================================+======================================================================================================================================================================+
| [Tech Tips](https://theaacn.org/disruptive-technology-initiative/dti-tech-tips/) for Clinical Neuropsychology | List of blogs and guides on using Technology in Clinical Neuropsychology | [Disruptive Technology Initiative](https://theaacn.org/disruptive-technology-initiative/) of the [American Academy of Clinical Neuropsychology](https://theaacn.org) |
+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                               |                                                                          |                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                               |                                                                          |                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Innovations for Clinical Neuropsychology.

# Outcome Measures

+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------+
| Outcome Measures                                                                      | Description                                                                                                                      | Contributor/s                              |
+=======================================================================================+==================================================================================================================================+============================================+
| The Lloyd & Preece Psychometric [Auto-Scorer](https://psychologywa.com/psychometric/) | Excel sheet designed by Dr Erin Lloyd and Dr David Preece, which auto-scores for a range of common psychological questionnaires. | Erin Lloyd, [David Preece](#drdavidpreece) |
+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------+
|                                                                                       |                                                                                                                                  |                                            |
+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------+
|                                                                                       |                                                                                                                                  |                                            |
+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------+

: Innovations for Clinical Neuropsychology.

# Podcasts

+--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| Podcasts                             | Description                                                                                                                           | Contributor                                                 |
+======================================+=======================================================================================================================================+=============================================================+
| [NavNeuro](https://www.navneuro.com) | The podcast where they present cutting-edge scientific findings, discuss important topic areas, and interview brain-behavior experts. | [John Bellone](https://x.com/johnabellone), Ryan Van Patten |
+--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                                      |                                                                                                                                       |                                                             |
+--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                                      |                                                                                                                                       |                                                             |
+--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+

: Tools and Applications for Clinical Neuropsychology.

# Tools

+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Tool / App                                                                                                 | Description                                                                                                                                                                            | Contributor                                                                                                |
+============================================================================================================+========================================================================================================================================================================================+============================================================================================================+
| [Easy Report](https://npscoresheet-b0f9fbefac84.herokuapp.com)                                             | Say goodbye to data cleaning and manual Excel tasks. **Easy Report** transforms reporting into a seamless, efficient process, allowing you to focus on delivering valuable insights.   | [Alexandra Davis](#alexneuropsych)                                                                         |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| [Reliable Change Calculators](https://www.navneuro.com/132/)                                               | A series of Excel sheets for easily calculating reliable change scores using manual entry of pre-populated for the RBANS                                                               | Kevin Duff                                                                                                 |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| [Calculators for Neuropsychology Practice](https://homepages.abdn.ac.uk/j.crawford/pages/dept/psychom.htm) | A huge range of downloadable (Windows) calculators for neuropsychology practice (e.g., regression, percentiles, single case-analysis, reliable change, supplementary test output etc.) | [John Crawford](https://homepages.abdn.ac.uk/j.crawford/pages/dept/index.html) and a series of co-authors. |
+------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+

: Tools and Applications for Clinical Neuropsychology.

# Tutorials

# Webinars

# Tests

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| Tests                                                                                                                                                                        | Description                                                                                                          | Contributor                                                                                     |
+==============================================================================================================================================================================+======================================================================================================================+=================================================================================================+
| [Neuropsychological Test Database](https://www.researchgate.net/publication/336605389_Neuropsychological_Tests_Cognitive_Assessments_-_Database_of_test-related_information) | This database includes information on 100+ neuropsychological tests/cognitive assessments, and self-report measures. | [Georgia Dunning](#georgiadunning8), [Alistair Teager](https://x.com/ajteager), Benjamin Dawson |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
|                                                                                                                                                                              |                                                                                                                      |                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
|                                                                                                                                                                              |                                                                                                                      |                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+

: Tests for Clinical Neuropsychology.
